---
- name: 9k facts
  hosts: NXOS
  connection: local
  tasks:
    - name: Run show version on nexus devices
      nxos_command:
        commands: show version
        host: "{{inventory_hostname}}"
        transport: nxapi
        use_ssl: yes
        validate_certs: no
      register: nxos_data

    - name: Print name to console
      debug: msg="{{nxos_data}}"
